[package]
name = "dvd-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
block-device = { path = "../../libs/block-device" }
xdvd = { path = "../../libs/xdvd" }
